version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORTS}
    volumes:
      - ${DB_VOLUMES}